# Generated by Django 3.1.3 on 2020-11-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a text decription'),
            preserve_default=False,
        ),
    ]
